
CREATE TABLE  Banestrekning (
	BaneNavn INTEGER NOT NULL,
	Fremdriftsenergi INTEGER,
	StartStasjon VARCHAR(30),
	EndeStasjon VARCHAR(30),
	DelSNavn VARCHAR(30),
	CONSTRAINT Bane_PK PRIMARY KEY (BaneNavn)
	CONSTRAINT Bane_FK1 FOREIGN KEY (DelSNavn) REFRENCES Dekstrekning(DelSNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE Delstrekning (
	DelSNavn INTEGER NOT NULL,
	LengdeIKm INTEGER,
	AntallSpor INTEGER NOT NULL,
	StartStasjon VARCHAR(30),
	EndeStasjon	VARCHAR(30),
	CONSTRAINT DelS_PK PRIMARY KEY (DelSNavn));


CREATE TABLE Jernbanestasjon (
	StasjonNavn	VARCHAR(30),
	moh	INTEGER,
	CONSTRAINT JernbaneS_PK PRIMARY KEY (StasjonNavn));


CREATE TABLE Togrute(
	RuteID INTEGER NOT NULL,
	Retning	INTEGER	NOT NULL,
	BaneNavn VARCHAR(30),
	OperatørNavn VARCHAR(30),
	CONSTRAINT Rute_PK PRIMARY KEY (RuteID)
	CONSTRAINT Rute_FK1 FOREIGN KEY (BaneNavn) REFRENCES Banestrekning(BaneNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT Rute_FK2 FOREIGN KEY (OperatørNavn) REFRENCES Operatør(OperatørNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE TogruteForekomst(
	TogruteForekomstID INTEGER NOT NULL,
	OperatørNavn VARCHAR(30),
	CONSTRAINT Forekomst_PK PRIMARY KEY (TogruteForekomstID)
	CONSTRAINT Rute_FK1 FOREIGN KEY (OperatørNavn) REFRENCES Operatør(OperatørNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE);



CREATE TABLE HarDelstrekning(
	TogruteForekomstID	INTEGER NOT NULL,
	DelSNavn VARCHAR(30),
	Ankomsttid INTEGER,
	Avgangstid 	INTEGER,
	CONSTRAINT HarDelS_PK PRIMARY KEY (TogruteForekomstID, DelSNavn)
	CONSTRAINT HarDelS_FK1 FOREIGN KEY (TogruteForekomstID) REFRENCES TogruteForekomst(TogruteForekomstID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT HarDelS_FK2 FOREIGN KEY (TogruteForekomstID) REFRENCES TogruteForekomst(TogruteForekomstID)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT HarDelS_FK3 FOREIGN KEY (DelSNavn) REFRENCES Delstrekning(DelSNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE);



CREATE TABLE HarTogruteForekomst(
	DelSNavn VARCHAR(30),
	BillettID INTEGER NOT NULL,
	CONSTRAINT HarTogF_PK PRIMARY KEY (DelSNavn, BillettID)
	CONSTRAINT HarTogF_FK1 FOREIGN KEY (DelSNavn) REFRENCES Delstrekning(DelSNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT HarTogF_FK2 FOREIGN KEY (BillettID) REFRENCES Billett(BillettID)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE Operatør(
	OperatørNavn VARCHAR(30),
	CONSTRAINT Operatør_PK PRIMARY KEY (OperatørNavn));


CREATE TABLE HarVogner(
	OperatørNavn VARCHAR(30),
	RegNr INTEGER NOT NULL,
	CONSTRAINT HarV_PK PRIMARY KEY (OperatørNavn, RegNr)
	CONSTRAINT HarV_FK1 FOREIGN KEY (OperatørNavn) REFRENCES Operatør(OperatørNavn)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT HarV_FK2 FOREIGN KEY (VognRegNr) REFRENCES Vogn(RegNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE Vogn(
	RegNr INTEGER NOT NULL,
	CONSTRAINT RegNr_PK PRIMARY KEY (RegNr));


CREATE TABLE Sittevogn(
	RegNr INTEGER NOT NULL,
	SeterPerRad	INTEGER,
	CONSTRAINT SitteV_PK PRIMARY KEY (RegNr)
	CONSTRAINT SitteV_FK1 FOREIGN KEY (RegNr) REFRENCES Vogn(RegNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE Sovevogn(
	RegNr INTEGER NOT NULL,
	AntallKupe	INTEGER,
	CONSTRAINT SitteV_PK PRIMARY KEY (RegNr)
	CONSTRAINT SitteV_FK1 FOREIGN KEY (RegNr) REFRENCES Vogn(RegNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE Plass(
	PlassNR	INTEGER NOT NULL,
	BillettID INTEGER NOT NULL,
	CONSTRAINT Plass_PK PRIMARY KEY (PlassNR, BillettID)
	CONSTRAINT Plass_FK1 FOREIGN KEY (BillettID) REFRENCES Billett(BillettID)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE Senger(
	SengNR INTEGER NOT NULL,
	PlassNr	INTEGER NOT NULL,
	CONSTRAINT Senger_PK PRIMARY KEY (SengNR, PlassNr)
	CONSTRAINT Senger_FK1 FOREIGN KEY (PlassNr) REFRENCES Plass(PlassNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE);


CREATE TABLE Seter(
	SeteNR INTEGER NOT NULL,
	PlassNr	INTEGER NOT NULL,
	CONSTRAINT Seter_PK PRIMARY KEY (SeteNR, PlassNr)
	CONSTRAINT Seter_FK1 FOREIGN KEY (PlassNr) REFRENCES Plass(PlassNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE);



CREATE TABLE Kundeordre(
	OrdreNr	INTEGER NOT NULL,
	Dato INTEGER,
	Tidspunkt INTEGER,
	KundeNr	INTEGER NOT NULL,
	CONSTRAINT KundeO_PK PRIMARY KEY (OrdreNr)
	CONSTRAINT KundeO_FK1 FOREIGN KEY (KundeNr) REFRENCES Kunde(KundeNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE);



CREATE TABLE OrdreForekomst(
	OrdreNr	INTEGER NOT NULL,
	TogruteForekomstID INTEGER NOT NULL,
	CONSTRAINT OrdreF_PK PRIMARY KEY (OrdreNr, TogruteForekomstID)
	CONSTRAINT OrdreF_FK1 FOREIGN KEY (OrdreNr) REFRENCES Plass(OrdreNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT OrdreF_FK2 FOREIGN KEY (TogruteForekomstID) REFRENCES TogruteForekomst(TogruteForekomstID)
		ON UPDATE CASCADE
		ON DELETE CASCADE);



CREATE TABLE Kunde(
	KundeNr	INTEGER NOT NULL,
	Navn VARCHAR(30),
	e-post VARCHAR(30),
	tlf	VARCHAR(10),
	CONSTRAINT Kunde_PK PRIMARY KEY (KundeNr));
	


CREATE TABLE OrdreForekomst(
	OrdreNr	INTEGER NOT NULL,
	TogruteForekomstID INTEGER NOT NULL,
	CONSTRAINT OrdreF_PK PRIMARY KEY (OrdreNr, TogruteForekomstID)
	CONSTRAINT OrdreF_FK1 FOREIGN KEY (OrdreNr) REFRENCES Plass(OrdreNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT OrdreF_FK2 FOREIGN KEY (TogruteForekomstID) REFRENCES TogruteForekomst(TogruteForekomstID)
		ON UPDATE CASCADE
		ON DELETE CASCADE);



CREATE TABLE Billett(
	BillettID INTEGER NOT NULL,
	OrdreNr	INTEGER NOT NULL,
	CONSTRAINT Billett_PK PRIMARY KEY (BillettID,)
	CONSTRAINT Billett_FK1 FOREIGN KEY (OrdreNr) REFRENCES Plass(OrdreNr)
		ON UPDATE CASCADE
		ON DELETE CASCADE);





